name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonarqube_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SonarQube Scan
        uses: cmuriukin/sonarqube-analysis-action@main
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          sonar-url: https://sonarqube.example.com
          project-key: your-project-key
          project-name: Your Project Name
          project-version: 1.0.0
          sources: ./
