name: My Workflow

on: [push]

jobs:
  sonarqube:
    runs-on: ubuntu-latest
    steps:
      - name: SonarQube Analysis
        uses: cmuriukin/sonarqube-analysis-action@v1
        with:
          sonar-token: ${{ secrets.SONAR_TOKEN }}
          project-key: my-project
          project-name: My Project
          project-version: 1.0.0
          sources: './src'
